version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: ligoj
      MYSQL_USER: ligoj
      MYSQL_PASSWORD: ligoj
  api:
    image: ligoj-api:1.6.9
    links:
      - db
    depends_on: 
      - db
  ui:
    image: ligoj-ui:1.6.9
    links:
      - api:ligoj-api
    ports: 
      - "8080:8080"
