version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: ligoj
      MYSQL_USER: ligoj
      MYSQL_PASSWORD: ligoj
  rest:
    image: ligoj-app-business:1.5.0
    links:
      - db
    depends_on: 
      - db
  web:
    image: ligoj-app-web:1.5.0
    links:
      - rest:ligoj-business
    ports: 
      - "8080:8080"
    environment: 
      - CUSTOM_OPTS=-Dsecurity=Trusted
